### ISSUE TITLE
Is the naming intentional?

### ISSUE THREAD

**Issue by Skeen** [Alfresco/acs-ingress#6]
The image is currently called `alfresco/acs-community-ngnix` specifically `ngnix` instead of `nginx`.

The project headline in the readme mentions `nginx`, so does the image name have a typo, or is it intentional?

**Comment by montgolfiere** [comment]
Thanks for the feedback. Yes, good spot, that does indeed look like a minor typo (I'm sure it was not intentional) :-)

I notice that acs-community-ngnix image is referenced in the ACS Community deployment template, eg. 

* https://github.com/Alfresco/acs-community-deployment/blob/master/docker-compose/docker-compose.yml#L146

FYI: I think this project actually builds & releases the alfresco-acs-nginx image (note: without the same typo):

* https://hub.docker.com/r/alfresco/alfresco-acs-nginx/tags 

which is referenced in ACS Enterprise deployment template(s), including:

* https://github.com/Alfresco/acs-deployment/blob/master/docker-compose/docker-compose.yml#L208

**Comment by montgolfiere** [comment]
cc @ancutam @anechifor @killerboot

**Comment by ancutam** [comment]
@Skeen, it is indeed an unfortunate typo. Thanks for pointing it out. The next image release will have the proper name.
